name: create-alfredworkflow-file
run-name: Create alfredworkflow file for release ${{ github.ref }}
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'link-opener.alfredworkflow'
        exclusions: '*.git*'
    - uses: actions/upload-artifact@main
      with:
        name: link-opener.alfredworkflow
        path: link-opener.alfredworkflow


